### ISSUE TITLE
#001: Current Session Button Visibility on Splash Screen

### ISSUE THREAD

**Issue by tonytonytoan** [trihan51/Game-On#5]
The Current Session Button should not be visible when you're on the Splash Screen.

**How to Recreate:**
1. Make sure you're logged out of Game On.
2. Exit out of the application.
3. Start up the application.
4. You should see "CURRENT SESSION" on the Action Bar.

**Expected Outcome:**

CURRENT SESSION button should not be visible when in Splash Screen.

![capture](https://cloud.githubusercontent.com/assets/9190572/13037191/7197bd8a-d330-11e5-9a48-82bdbbf5ffcb.PNG)

**Comment by trihan51** [comment]
Prasamsha fixed this defect in sprint 2. if it occurs again, please reopen this issue. Thanks, Tony.
