### ISSUE TITLE
#002: LogOut Button Visibility on Login Screen Action Overflow

### ISSUE THREAD

**Issue by tonytonytoan** [trihan51/Game-On#6]
The LogOut Button should not be visible when you're on the Splash Screen.

**How to Recreate:**

Make sure you're logged out of Game On.
Exit out of the application.
Start up the application.
Click on the Action Overflow button on the Action Bar.
You should see "LogOut" in the overflow.

**Expected Outcome:**

LogOut button should not be visible when you are not logged in.

![capture](https://cloud.githubusercontent.com/assets/9190572/13037215/d80763e0-d330-11e5-8e04-033038ed0bdb.PNG)

**Comment by trihan51** [comment]
Prasamsha fixed this defect in sprint 2. If it occurs again, please reopen this issue.
